---
name: discordv3
author: YuriTotoso
main: YuriTotoso\discordv3\Main
version: 1.0.0
api:
- 3.0.0
- 4.0.0
commands:
  dc:
    permission: dcv3.use
    permission-message: '§cWithout Permision!'
    description: 'See Your SERVER's Discord Link'
permissions:
  dcv3.use:
    default: true
...
